### ISSUE TITLE
您好，我ios项目构建时遇到了 fatal error: 'AdEvent.h' file not found     #import "AdEvent.h" 的错误，始终无法构建成功，请问有什么可能的原因和解决方案吗？

### ISSUE THREAD

**Issue by git-zhangc** [FlutterAds/flutter_qq_ads#11]

**Comment by BytesZero** [comment]
可以截图错误并且提供一下版本吗？

**Comment by BytesZero** [comment]
@git-zhangc  可否提供更多的信息

**Comment by git-zhangc** [comment]
![1631928952461](https://user-images.githubusercontent.com/54786917/133868032-1fb2f247-6c99-4929-9b37-eb00aa281acd.jpg)
![1631929117952](https://user-
![WechatIMG158](https://user-images.githubusercontent.com/54786917/133868038-7db98a05-3b90-4fa6-9481-759ea189f8bc.jpeg)
images.githubusercontent.com/54786917/133868037-b31276a2-b503-433e-915d-73bfb4149405.jpg)

**Comment by git-zhangc** [comment]
![1631928952461](https://user-images.githubusercontent.com/54786917/133868032-1fb2f247-6c99-4929-9b37-eb00aa281acd.jpg)
![WechatIMG158](https://user-images.githubusercontent.com/54786917/133868038-7db98a05-3b90-4fa6-9481-759ea189f8bc.jpeg)
images.githubusercontent.com/54786917/133868037-b31276a2-b503-433e-915d-73bfb4149405.jpg)
![1631929117952](https://user-images.githubusercontent.com/54786917/133868081-6296a5d0-4a37-43b2-b350-271abbbefd9a.jpg)
这是我的错误截图和 flutter版本 ，并且我的项目同时应用了穿山甲和 广点通插件

**Comment by BytesZero** [comment]
可以去这个路径把下载的依赖删除掉，然后重新 flutter clean 一下，在运行看看
![image](https://user-images.githubusercontent.com/8764899/133868226-9349a7c1-6030-4fcd-80cc-94a1ef9da2b7.png)

**Comment by git-zhangc** [comment]
好的，我试一下

**Comment by git-zhangc** [comment]
我删除了这个路径下的依赖，并且flutter clean 还是同样的错误， 然后我尝试删除Podfile.lock 和 Pods 文件夹  执行 flutter clean 再次编译也是 同样的错误

**Comment by BytesZero** [comment]
收到，我排查一下，提供一下 Flutter 版本信息，以及 iOS 的 Podfile 文件

**Comment by BytesZero** [comment]
问题我复现了，是我这边两个库同时使用的场景没有做好处理，我想想解决办法，然后继续同步

**Comment by git-zhangc** [comment]
我分别尝试了单独引用flutter_qq_ads 或 flutter_pangle_ads 都可以成功编译，是不是是同时引用两个插件导致的

**Comment by BytesZero** [comment]
非常感谢反馈，有新进展了我在这里通知

**Comment by BytesZero** [comment]
排查出问题是因为原生端基础架构相同，所以很多类名相同导致出现了冲突，初步找到解决办法，但是感觉不够优雅，正在寻找更优的解决办法，需要些时间，耐心等待

**Comment by BytesZero** [comment]
目前已经解决，将在 `v1.3.0|v2.3.0` 版本中解决

**Comment by git-zhangc** [comment]
好的，🙏

**Comment by BytesZero** [comment]
@git-zhangc  新版本已发布 `v1.3.0 | v2.3.0`
https://github.com/FlutterAds/flutter_qq_ads/releases/
