### ISSUE TITLE
支持视频贴片视频

### ISSUE THREAD

**Issue by nnianhouss** [FlutterAds/flutter_qq_ads#12]
App是视频类的，想在开头或者片尾播放广告

**Comment by BytesZero** [comment]
@nnianhou-  视频贴边暂时不支持，等信息流做完后，可能会加上。

**Comment by BytesZero** [comment]
@nnianhou-  我看贴片视频是在信息流这块包含的，现在 v1.4.0 或 v2.4.0 已支持信息流，可以试试，不过目前没有视频监听时间的回调返回给 Flutter 层
