### ISSUE TITLE
安卓信息流不点击不曝光，和其他插件一样

### ISSUE THREAD

**Issue by eatfishs** [FlutterAds/flutter_qq_ads#14]

**Comment by BytesZero** [comment]
有日志吗？或者数据验证吗？

**Comment by eatfishs** [comment]
有测试数据（量小可能参考性较差），主要是在日志中发现，信息流展示时未触发onAdExposure事件
![1639099140(1)](https://user-images.githubusercontent.com/45836182/145501024-8e346aca-4420-4a3c-a5f2-d2ca94ad6d37.png)

**Comment by BytesZero** [comment]
可以问问客服，是不是有停留时间才算

**Comment by BytesZero** [comment]
量确实有些小，我这边也再观察一下

**Comment by eatfishs** [comment]
测试时每条信息流等待事件均超过一分钟

**Comment by BytesZero** [comment]
@eatfishs  有最新的测试数据了吗？我这边测试曝光是正常的

**Comment by zytabcd123** [comment]
![image](https://user-images.githubusercontent.com/11885452/146105363-4654a015-5b22-4ec9-bab9-31531b587e8b.png)
曝光确实有问题

**Comment by BytesZero** [comment]
@zytabcd123  收到，我继续排查一下

**Comment by BytesZero** [comment]
Android 存在曝光问题，目前我正在和官方的人排查，暂时没有定位到问题点，iOS 正常目前测试

**Comment by BytesZero** [comment]
目前排查出来是 `onRenderSuccess` 后就立马  `onADClosed` 了，工单正在进行中，稍后有新进展继续回复

**Comment by BytesZero** [comment]
目前的进度是，广告点击后才会走曝光，正在继续跟进工单

**Comment by BytesZero** [comment]
提了工单也无法解决，暂时没有好的办法，继续尝试

**Comment by BytesZero** [comment]
后续有新版本了再尝试看看

**Comment by ksxkq** [comment]
感觉和广告位的 focus 有关，如果不能 focus 就无法曝光

**Comment by BytesZero** [comment]
广告位没有任何需要focus 的内容呢

**Comment by ksxkq** [comment]
> 

这里我也只是猜测嘛，广告位的曝光条件，一般都是需要有足够的可视区域；不允许被其它 View 遮挡；必须是 focus enable；
最近我也是遇到曝光失败，但是只要点击广告位，又会立马回调曝光成功的情况，后来发现是 focus 的设置问题

**Comment by kennir** [comment]
请问这个问题现在解决了吗？

**Comment by BytesZero** [comment]
已更新 v2.6.0，试试看
