### ISSUE TITLE
请教问题：使用Admob中介的情况，应该如何处理呢？

### ISSUE THREAD

**Issue by sunjianan9900** [FlutterAds/flutter_qq_ads#15]
之前一直使用的Admob，然后最近才申请到的优量汇。
想问一下，使用Admob的中介功能，后台配置好优量汇的情况下，客户端应该是怎样的呢？
引入该插件并初始化后，在调用广告的地方如果只使用admob的广告展示代码，会不会自动通过中介显示优量汇的广告呢？

**Comment by BytesZero** [comment]
Admob 是聚合插件，暂时不支持，可以关注我的 [GroMore 插件](https://github.com/FlutterAds/flutter_gromore_ads)
本插件需要单独使用优量汇广告位，我认为是无法使用admob的广告展示代码的。

**Comment by sunjianan9900** [comment]
> Admob 是聚合插件，暂时不支持，可以关注我的 [GroMore 插件](https://github.com/FlutterAds/flutter_gromore_ads) 本插件需要单独使用优量汇广告位，我认为是无法使用admob的广告展示代码的。

感谢回复🙏

**Comment by yy1300326388** [comment]
不客气

**Comment by BytesZero** [comment]
> > Admob 是聚合插件，暂时不支持，可以关注我的 [GroMore 插件](https://github.com/FlutterAds/flutter_gromore_ads) 本插件需要单独使用优量汇广告位，我认为是无法使用admob的广告展示代码的。
> 
> 感谢回复🙏

不客气，可以点个 Star 支持一下项目

**Comment by sunjianan9900** [comment]
已支持～

**Comment by BytesZero** [comment]
感谢🎉
