### ISSUE TITLE
经过测试安卓信息流广告在无网络情况下崩溃

### ISSUE THREAD

**Issue by nnianhouss** [FlutterAds/flutter_qq_ads#16]
-[FAQFeedAdLoad nativeExpressAdFailToLoad:error:] error:Error Domain=GDTAdErrorDomain Code=3001 "网络错误" UserInfo={NSLocalizedDescription=网络错误}
flutter: adIndex:0
Lost connection to device.

**Comment by BytesZero** [comment]
收到

**Comment by nnianhouss** [comment]
安卓崩溃日志

E/AndroidRuntime( 3106): FATAL EXCEPTION: main
E/AndroidRuntime( 3106): Process: com.banjixiaoguanjia.app, PID: 3106
E/AndroidRuntime( 3106): java.lang.IllegalArgumentException: Unsupported value: '[Ljava.util.List;@c6a83cc' of type 'class [Ljava.util.List;'
E/AndroidRuntime( 3106): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:292)
E/AndroidRuntime( 3106): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime( 3106): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 3106): 	at com.zero.flutter_qq_ads.load.FeedAdLoad.onNoAD(FeedAdLoad.java:133)
E/AndroidRuntime( 3106): 	at com.qq.e.ads.nativ.NativeExpressAD.b(Unknown Source:8)
E/AndroidRuntime( 3106): 	at com.qq.e.ads.AbstractAD$2.run(Unknown Source:4)
E/AndroidRuntime( 3106): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3106): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3106): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 3106): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 3106): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3106): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 3106): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process ( 3106): Sending signal. PID: 3106 SIG: 9
Lost connection to device.

**Comment by BytesZero** [comment]
已复现处理中

**Comment by BytesZero** [comment]
可以使用 github 2x 分支的测试啦
```yaml
dependencies:
    flutter_qq_ads:
        git:
            url: git@github.com:FlutterAds/flutter_qq_ads.git
            ref: 2x
```
