### ISSUE TITLE
信息流能支持设置静音吗?

### ISSUE THREAD

**Issue by nnianhouss** [FlutterAds/flutter_qq_ads#17]
（可选方法）指定视频广告的播放配置，配置包含：
1. autoPlayPolicy，指定不同网络下的视频播放策略，可选项包括：AutoPlayPolicy.WIFI（WiFi 网络自动播放，4G 网络手动点击播放），AutoPlayPolicy.ALWAYS（WiFi 和4G 网络都自动播放），默认值为 AutoPlayPolicy.ALWAYS。
2. autoPlayMuted，指定视频自动播放时是否静音，可选项包括：true（自动播放时静音），false（自动播放时有声），默认值为 true。
注：AutoPlayPolicy.ALWAYS 的配置能够一定程度优化广告收益
3. detailPageMuted，指定视频详情页是否静音播放，可选项包括：true（视频详情页静音播放），false（视频详情页有声播放），默认值为 false。
我看文档有这个参数设置

**Comment by nnianhou-** [comment]
还有插屏广告能支持静音吗？现在是视频app有声音的广告会自动播放把app声音覆盖掉

**Comment by BytesZero** [comment]
可以，我下个版本加上

**Comment by BytesZero** [comment]
现在应该模式就是静音的啦 已更新 v2.6.0
