### ISSUE TITLE
关于视频广告会影响fijkplayer播放器声音问题

### ISSUE THREAD

**Issue by nnianhouss** [FlutterAds/flutter_qq_ads#18]
播放器版本：fijkplayer: ^0.10.1
手机默认静音状态
系统：iOS

1.经过下载Demo集成fijkplayer在主页跟信息流页面手机静音测试，显示了视频广告后播放器声音消失。
2.广告设置静音播放也会影响播放器声音。
3.不展示视频广告情况下，手机静音模式播放器是有声音的，只有视频广告展示后就影响了播放器
4.经过测试只要是视频广告都会影响

目前通过播放器重新设置音量都无法再次播放声音，不知道是不是广告影响的。

如下代码可以加到Demo工程主页或者信息流进行测试验证

// 播放

    final FijkPlayer player = FijkPlayer();

    player.setDataSource('http://player.alicdn.com/video/aliyunmedia.mp4',
        autoPlay: true);

     SliverToBoxAdapter(
                child: FijkView(
              height: MediaQuery.of(context).size.width / (16 / 9),
              player: player,
            ))

**Comment by nnianhouss** [comment]
穿山甲广告测试：
同样的情况下，穿山甲视频广告就没问题，不会影响播放器

**Comment by BytesZero** [comment]
暂时不处理
测试一下 v2.6.0 看看
