### ISSUE TITLE
如何实现 应用下载弹窗确认？请求实现此功能 

### ISSUE THREAD

**Issue by dev-zl** [FlutterAds/flutter_qq_ads#22]
[https://developers.adnet.qq.com/doc/android/union/union_download_confirm](https://developers.adnet.qq.com/doc/android/union/union_download_confirm)
在广告播放中(广告展示和落地页)，点击触发广告下载时对开发者注册的回调函数进行回调，开发者可以使用回调获取应用名称、版本等相关信息，并进行弹窗提示用户是否确认进行下载。
适用场景：在合规的场景，点击下载类广告必须向用户展示应用信息并二次确认是否下载，而sdk的内部弹窗的格式不符合开发者UI要求的时候。

有助于应用更加合理合规

**Comment by BytesZero** [comment]
好的，我看看

**Comment by BytesZero** [comment]
暂时不支持
