### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel flutter_qq_ads_event)

### ISSUE THREAD

**Issue by Kayouyou** [FlutterAds/flutter_qq_ads#23]
iOS 正常，Android 跑真机有这个异常。

**Comment by BytesZero** [comment]
可否复现或者你设置事件的时机是什么时候呢？

**Comment by Kayouyou** [comment]
![截屏2022-05-09 10 31 46](https://user-images.githubusercontent.com/13092497/167330744-d4611470-1b4e-4db2-9e42-c7bf941931cd.png)

在main()中初始化，具体开屏广告是在自定义的splashscreen中拉取的。注释拉取开屏广告代码，只保留初始化代码同样报这个错误，安卓一直可以复现，iOS的正常。

**Comment by Kayouyou** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] **Unhandled Exception: MissingPluginException(No implementation found for method initAd on channel flutter_qq_ads)**
E/flutter (31862): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (31862): <asynchronous suspension>
E/flutter (31862): #1      FlutterQqAds.initAd (package:flutter_qq_ads/flutter_qq_ads.dart:30:25)
E/flutter (31862): <asynchronous suspension>


The following MissingPluginException was thrown while activating platform stream on channel flutter_qq_ads_event:
**MissingPluginException(No implementation found for method listen on channel flutter_qq_ads_event)**

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:516:9)
<asynchronous suspension>

**Comment by BytesZero** [comment]
你来个最小可复现的 Demo 把，并且把你的 flutter 版本和项目版本，引用插件的版本都贴出来

**Comment by Kayouyou** [comment]
好的，我稍后抽个时间弄个demo，谢谢

**Comment by BytesZero** [comment]
可以的，好了我复现一下，看看有解决方案或者插件修复

**Comment by Courser123** [comment]
佬大, 这个问题现在依然存在, demo都跑不起来

**Comment by BytesZero** [comment]
发一下Flutter版本和复现Demo
