### ISSUE TITLE
请教下如何去掉安卓：QUERY_ALL_PACKAGES permission

### ISSUE THREAD

**Issue by gushedaoren** [FlutterAds/flutter_qq_ads#24]
因为需要上架google play需要去掉QUERY_ALL_PACKAGES permission

请教下如何实现GlobalSetting的设置？

// 建议在初始化 SDK 前进行此设置
GlobalSetting.setEnableCollectAppInstallStatus(true);

参考连接：
https://developers.adnet.qq.com/doc/android/union/union_private_data_guide

**Comment by BytesZero** [comment]
@gushedaoren 
这个需要你单独开发处理或者加我微信 `toponelan` 私聊我帮你处理

**Comment by gushedaoren** [comment]
> 

有个更方便的解决方案，在AndroidManifest.xml文件里添加：
  <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"
        tools:node="remove"/>

**Comment by gushedaoren** [comment]
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"
        tools:node="remove"/>

**Comment by gushedaoren** [comment]
<img width="646" alt="权限截图" src="https://user-images.githubusercontent.com/2127677/186177815-561db865-ab81-4f67-9fa0-85e2b0cdedb9.png">
