### ISSUE TITLE
请问怎么解决弹出广告后的点击穿透问题

### ISSUE THREAD

**Issue by aolin59421** [FlutterAds/flutter_qq_ads#25]
是我自己写的一个插件但是无法解决弹出原生页面后点击穿透的问题，网上查的解决办法不适用，也是看到大佬也是弹SDK内容类型的插件    flutter我是菜鸟不怎么懂   但是又没在原生代码里看到相关的处理  所以想问一下怎么解决的     拜谢

**Comment by BytesZero** [comment]
什么类型的广告哪个平台

**Comment by aolin59421** [comment]
> 什么类型的广告在哪个平台

GDT 快手 穿山甲都有做 主要是开屏插屏全屏激励

**Comment by BytesZero** [comment]
什么类型的广告，是开屏还是激励视频还是啥？

**Comment by aolin59421** [comment]
> 什么类型的广告，是开屏还是激励视频还是啥？

插屏、全屏和激励

**Comment by BytesZero** [comment]
Android  还是 iOS 呢，可否来个视频
