### ISSUE TITLE
大佬可以更新个版本吗，好久没更新过版本了。

### ISSUE THREAD

**Issue by wangxude** [FlutterAds/flutter_qq_ads#28]
7月20号优量汇更新了版本。修复了挺多问题
https://developers.adnet.qq.com/doc/android/union/union_version，大佬可以更新下广告插件吗

**Comment by BytesZero** [comment]
近期会更新一下，稍等一下，太忙了

**Comment by BytesZero** [comment]
@wangxude 已更新 v2.6.0

**Comment by wangxude** [comment]
感谢大佬更新版本
