### ISSUE TITLE
请问开屏广告出现加载不出来，并且一瞬间就关闭了

### ISSUE THREAD

**Issue by sjm1099** [FlutterAds/flutter_qq_ads#30]
不知什么版本突然开始，它的开屏广告就有这个问题了

**Comment by BytesZero** [comment]
首先看一下日志，如果不懂可以去找找文档，如果还不行就把日志和Flutter 版本发出来
----
提问之前请先点击一下 Star ，免费支持一下

**Comment by winter-tech** [comment]
> ## 首先看一下日志，如果不懂可以去找找文档，如果还不行就把日志和Flutter 版本发出来
> 提问之前请先点击一下 Star ，免费支持一下

D/AdSplashActivity(28955): onADTick millisUntilFinished：5996
E/gdt_ad_mob(28955): 广告容器的高度必须 >= 手机的高度 * 0.95，否则将不进行曝光上报和计费，当前的高度为：627dp
D/AdSplashActivity(28955): onNoAD adError:广告容器尺寸错误。
D/PluginDelegate(28955): EventChannel addEvent event:{adId=81318279046, errCode=4005, errMsg=广告容器尺寸错误。, action=onAdError}
I/flutter (28955): ---------- adId:81318279046 action:onAdError
I/flutter (28955): -------- errCode:4005 errMsg:广告容器尺寸错误。

提示这个报错，没有传logo
