### ISSUE TITLE
请问目前只支持开屏广告吗?

### ISSUE THREAD

**Issue by BadReese** [FlutterAds/flutter_qq_ads#5]
如题

**Comment by BadReese** [comment]
而且不是空安全的啊..

**Comment by BytesZero** [comment]
文档已更新，目前支持：
- 开屏
- 插屏
- 激励视屏

> 有空安全版本和非空安全版本，详情请看最新的文档说明哦

**Comment by BytesZero** [comment]
回复晚了，非常抱歉，如没有正确回复您的问题，请联系我打开

**Comment by BytesZero** [comment]
可以查看我的[ BP 项目面板](https://github.com/FlutterAds/flutter_qq_ads/projects/1)

**Comment by BytesZero** [comment]
最新版本已支持【开屏、插屏、激励视频、全屏视频】
